baseURL = 'http://cliford.net/'
languageCode = 'en-in'
title = 'Portfolio'
theme = 'LoveIt'

# enableGitInfo = true
enableEmoji = true

# Author config
[author]
  name = "Cliford"
  email = "reach@cliford.net"

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "Resume"
    pre = ""
    post = '<i class="arrow-up-right-from-square"/>' #fontawesome icon
    name = "Resume"
    url = "#"
    title = ""

[params]
  defaultTheme = "dark"
  # public git repo url only then enableGitInfo is true
  gitRepo = "https://github.com/clifordjoshy/clifordjoshy.github.io"
  # website title for Open Graph and Twitter Cards
  title = "Random Ramblings"
  description = "This is where i will randomly ramble."
  # website images for Open Graph and Twitter Cards
  images = ["/logo.png"]
	  # Header config
  [params.header]
    # LoveIt NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "cliford's blog"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""

# Footer config
  [params.footer]
    enable = true
    # LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
    custom = ''
    # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
    hugo = true
    # LoveIt NEW | 0.2.0 whether to show copyright info
    copyright = true
    # LoveIt NEW | 0.2.0 whether to show the author
    author = true
    # Site creation time
    since = 2022
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

	# Home page config
  [params.home]
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # URL of avatar shown in home page
      avatarURL = "/avatar.jpeg"
      title = "Hello! I'm Cliford"
      # subtitle shown in home page (HTML format is supported)
      subtitle = "A developer, a linux enthusiast and a tiling window manager supremacist"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      disclaimer = "i am not responsible."

# Social config about the author
  [params.social]
    GitHub = "clifordjoshy"
    Linkedin = "cliford-joshy-15b648190"
    Discord = "PaperStache#5235"
		StackOverflow="xx"
    Email = "reach@cliford.net"
    RSS = true # LoveIt NEW | 0.2.0

  [params.typeit]
    # typing speed between each step (measured in milliseconds)
    speed = 50
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 1000
    # character used for the cursor (HTML format is supported)
    cursorChar = "|"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration = -1

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false