name: github pages

on:
  push:
    branches:
      - main
  schedule:
    # Run at 01:01 UTC on January 1st of every year
    - cron: "1 1 1 1 *"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Compile Resume
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: resume
          root_file: main.tex
          post_compile: cp main.pdf ../static/resume.pdf

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          # this is the max hugo version that LoveIt 0.3.0 supports
          hugo-version: "0.145.0"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
